In [8]:
colors=input()
new_list=[x for x in colors if 'l' in x]
print(new_list)

 blue , purple , blue , yellow


['l', 'l', 'l', 'l', 'l']


In [12]:
colors=input()
new_list=[x for x in colors if 'l' in x]
print(new_list)

 c


[]


In [41]:
import numpy as np
a = np.array([[1, 2, 3],
              [4, 5, 6]])
print(a)
a=a.reshape(3,2)
print(a)




[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [22]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
a.shape

(2, 3)

In [39]:
import numpy as np 
a = np.array([1, 2, 3, 4, 5, 6])
b=np.array([[1,2,3],[4,5,6]])
c=np.array([[1,2,3],[4,5,6],[1,2,3],[4,5,6]])
print(a,b,c ,sep='\n',end='\n')
print(a.ndim,b.ndim,c.ndim,sep='\n')
print("item size",a.itemsize,b.itemsize,c.itemsize,"bytes")
print(a.size,b.size,c.size)
print(a.shape,b.shape,c.shape)


[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
1
2
2
item size 8 8 8 bytes
6 6 12
(6,) (2, 3) (4, 3)


In [42]:
import numpy as np
a = np.array([[1, 2, 3],
              [4, 5, 6]])
print(a[0,2],a[1,1])

3 5


In [45]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(a[1:7:2])
print(a.dtype)

[2 4 6]
int64


In [55]:
import numpy as np
a = np.array([[1, 2, 3],[4, 5, 6]])
b = np.array([[1, 2, 3],[4, 5, 6]])
arr=np.concatenate((a,b),axis=1)
c=np.concatenate((a,b),axis=0) #default axis=0
print(arr)
print(c)

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [56]:
import numpy as np
a=np.array([1,2,3,4,5,6],dtype='S')
print(a)
print(a.dtype)


[b'1' b'2' b'3' b'4' b'5' b'6']
|S1


In [58]:
import numpy as np
a=np.array([1,2,3,4,5,6])
print(a)
print(a.dtype)
new_arr=a.astype('S')
print(new_arr.dtype)

[1 2 3 4 5 6]
int64
|S21
